

const Map<String,String> en_US = {


  "Cancel":'Cancel',
  "DerivationInputs":"Derivation Inputs",
  "VaultIndex":'Vault Index',
  "Input":'Input',
  "Chain":'Chain',
  "ImportFile":'import File',
  "DropFile":'Drop your files here',
  "MaximumSize":'Maximum size: 500M',
  "MnemonicWord":'Mnemonic word',
  "EciesKEY":'ECIES KEY',
  "RSAKey":'RSA KEY',
  "Generate":'Generate Child Extended Private KEY',
  "Address":'Address',
  "ChildExtended":'Child Extended Private Key',
  "FileUploaded":'File Uploaded',
  "RestoredSuccess":"Recovery  Successfully",
  "Confirm":"Confirm",
  "ChooseChain":"Choose Chain",
  "RestoredFailed":"Recovery  Failed",
  "CompleteParameters":"Please complete the parameters",
  "input1":"Please fill in the team's wallet quantity correctly",
  "Export":"Export",
  "PleaseImport":"Please import the compressed file",
  "EnterAmount":"Please enter the wallet amount",
  "EnterNet":"Please select a network",
  "MnemonicFailed":"Please enter the mnemonic",
  "InputEcies":"Please Enter ECIES KEY",
  "search":'Input Search Name',
  "dragNotice":'Please drag the Secret Key file here',
  "dragNotice2":'Please drag the RAS Key file here',
  "paste":'paste',
  "chainName":'Chain Name',
  "title":"HyperBC Vault Key Derivation Tool",
  "loading":'loading',
  "clear":'Clear',
};