

const Map<String,String> en_US = {


  "Cancel":'Cancel',
  "DerivationInputs":"Derivation Inputs",
  "VaultIndex":'Vault Index',
  "Input":'Input',
  "Chain":'Chain',
  "ImportFile":'import File',
  "DropFile":'Drop your files here',
  "MaximumSize":'Maximum size: 500M',
  "MnemonicWord":'Mnemonic word',
  "EciesKEY":'ECIES KEY',
  "RSAKey":'RSA KEY',
  "Generate":'Generate Child Extended Private KEY',
  "Address":'Address',
  "ChildExtended":'Child Extended Private Key',
  "FileUploaded":'File Uploaded',
  "RestoredSuccess":"Recovery  Successfully",
  "Confirm":"Confirm",
  "ChooseChain":"Choose Chain",
  "RestoredFailed":"Recovery  Failed",
  "CompleteParameters":"Please complete the parameters",
  "input1":"Please fill in the team's wallet quantity correctly",
  "Export":"Export",
  "PleaseImport":"Please import the compressed file",
  "EnterAmount":"Please enter the wallet amount",
  "EnterNet":"Please select a network",
  "MnemonicFailed":"Please enter the mnemonic",
  "InputEcies":"Please Enter ECIES KEY",
  "search":'Input Search Name',
  "dragNotice":'Please drag the Secret Key file here',
  "dragNotice2":'Please drag the RSA Key file here',
  "paste":'paste',
  "chainName":'Chain Name',
  "title":"CipherBC Vault Key Derivation Tool",
  "loading":'loading',
  "clear":'Clear',
  "RecoveryKey":'Recover private key',
  "EDDSATransfer":'EDDSA transfer',
  "CheckBalance":'Check balance',
  "TransferCurrency":'Transfer currency',
  "TransferWaring":'Currently, the EdDSA private keys exported by Solana, Aptos, and Polkadot do not support wallet import. If you need to transfer money, you can use the EdDSA transfer tool through the restored private key.',
  "TransferWaring2":'Please check the tokens and gess fee when transferring out to avoid failure.',
  "ToAddress":'To (address)',
  "FromKey":'From (private key)',
  "TransferAmount":'Amount',
  "CustomRPC":'Customizable RPC nodes',
  "EnsureTransfer":'Confirm to transfer out',
  "TransferDeclaration":'Note the transfer instructions:',
  "Declaration1":'1. Confirming the transfer means that you agree to the client’s online operation for on-chain broadcast.',
  "Declaration2":'2. For offline signature, it will generate a signed message code on the client side. Please copy the message code and entrust a third party to perform the on-chain broadcast transaction.',
  "BlockExplorer":'Copy the address from the CipherBC application and go to the block explorer to query》',
  "CustomCoin":'Customized currency',
  "RightKey":'Please enter the correct private key',
  "RightContract":'Please enter the correct contract',
  "RightAddress":'Please enter correct address',
  "RightAmount":'Please enter the correct amount',
  "BlockExplorerQuery":'You can go to the block explorer to view the account details',
  "Submitted":'Submitted',
  "Go":'Go to',
  "Failed":'fail',
  "knew":'Knew',
  "noNet":'Please connect to the network',
  "HintAmount":'Please enter amount',
  "HintKey":'Please enter the recovered private key',
  "HintAddress":'Please enter the receiving address',
  "HintContract":'Please enter the smart  contract of the currency',
  "HintRPC":'Please enter the RPC address',
};