

const Map<String ,String> zh_CN = {

  "Cancel":'取消',
  "DerivationInputs":"推导输入",
  "VaultIndex":'钱包数量',
  "Input":'请输入',
  "Chain":'链',
  "ImportFile":'导入文件',
  "DropFile":'请将您的文件放到此处',
  "MaximumSize":'最大尺寸: 500M',
  "MnemonicWord":'助记词',
  "EciesKEY":'ECIES 密钥',
  "RSAKey":'RSA 密钥',
  "Generate":'生成全部私钥',
  "Address":'地址',
  "ChildExtended":'子私钥',
  "FileUploaded":'文件上传成功',
  "RestoredSuccess":"恢复成功",
  "Confirm":"确认",
  "ChooseChain":"请选择链",
  "RestoredFailed":"恢复失败",
  "CompleteParameters":"请完善信息",
  "input1":"请正确填写团队的钱包数量",
  "Export":"导出",
  "PleaseImport":"请导入压缩文件",
  "EnterAmount":"请输入钱包数量",
  "EnterNet":"请选择网络",
  "MnemonicFailed":"请输入助记词",
  "InputEcies":"请输入ECIES KEY",
  "search":'搜索名称',
  "dragNotice":'请将Secret Key文件拖入此处',
  "dragNotice2":'请将RSA Key文件拖入此处',
  "paste":'粘贴',
  "chainName":'链名',
  "title":"CipherBC私钥恢复工具",
  "loading":'加载中',
  "clear":'清空',
};