

const Map<String ,String> zh_CN = {

  "Cancel":'取消',
  "DerivationInputs":"推导输入",
  "VaultIndex":'钱包数量',
  "Input":'请输入',
  "Chain":'链',
  "ImportFile":'导入文件',
  "DropFile":'请将您的文件放到此处',
  "MaximumSize":'最大尺寸: 500M',
  "MnemonicWord":'助记词',
  "EciesKEY":'ECIES 密钥',
  "RSAKey":'RSA 密钥',
  "Generate":'生成全部私钥',
  "Address":'地址',
  "ChildExtended":'子私钥',
  "FileUploaded":'文件上传成功',
  "RestoredSuccess":"恢复成功",
  "Confirm":"确认",
  "ChooseChain":"请选择链",
  "RestoredFailed":"恢复失败",
  "CompleteParameters":"请完善信息",
  "input1":"请正确填写团队的钱包数量",
  "Export":"导出",
  "PleaseImport":"请导入压缩文件",
  "EnterAmount":"请输入钱包数量",
  "EnterNet":"请选择网络",
  "MnemonicFailed":"请输入助记词",
  "InputEcies":"请输入ECIES KEY",
  "search":'搜索名称',
  "dragNotice":'请将Secret Key文件拖入此处',
  "dragNotice2":'请将RSA Key文件拖入此处',
  "paste":'粘贴',
  "chainName":'链名',
  "title":"CipherBC私钥恢复工具",
  "loading":'加载中',
  "clear":'清空',
  "RecoveryKey":'恢复私钥',
  "EDDSATransfer":'EDDSA转账',
  "CheckBalance":'查询余额',
  "TransferCurrency":'转出币种',
  "TransferWaring":'目前Solana、Aptos、Polkadot导出的是EdDSA 私钥不支持钱包导入的方式，您需要转账可以通过恢复的私钥使用EdDSA 转账工具完成。',
  "TransferWaring2":'1.转出时请检查下余额，确保转出代币和GAS充足，避免因代币或GAS不足导致的失败 \n2.避免资金损失，转出DOT填写数量需 > 1',
  "TransferWaring3":'2.避免资金损失，转出DOT填写数量需 > 1',
  "ToAddress":'To（地址）',
  "FromKey":'From（私钥）',
  "TransferAmount":'转出数量',
  "CustomRPC":'可自定义RPC节点',
  "EnsureTransfer":'确认转出',
  "TransferDeclaration":'注意：确认转出，表示您同意客户端上链广播交易的联网操作',
  "Declaration1":'确认转出，表示您同意客户端联网进行链上广播交易的联网操作',
  "Declaration2":'2.离线签名，客户端将生成一段已签名的消息码，您需复制消息码并委托第三方进行上链广播交易',
  "BlockExplorer":'请复制地址后前往区块浏览器查询 >',
  "CustomCoin":'自定义币种',
  "RightKey":'请输入正确的私钥',
  "RightContract":'请输入正确的合约',
  "RightAddress":'请输入正确的地址',
  "RightAmount":'请输入正确的数量',
  "BlockExplorerQuery":'可前往区块浏览器查看到账详情',
  "Submitted":'已提交',
  "Go":'前往',
  "Failed":'失败',
  "knew":'知道了',
  "noNet":'请链接网络',
  "HintAmount":'请输入数量',
  "HintKey":'请输入恢复的私钥',
  "HintAddress":'请输入接收的地址',
  "HintContract":'请输入币种合约',
  "HintRPC":'请输入RPC地址',
  "copy":'复制成功',
  "recovery_waring":"注意：点击“生成全部私钥”，客户端将离线生成指定链的子私钥和对应地址",
  "recovery_waring1":"1.生成的子私钥，您可以通过第三方应用导入钱包进行恢复。请及时做好安全备份并妥善保存。",
  "recovery_waring2":"2.生成的地址，您可以前往对应区块浏览器查询余额。",
  "transferConfirmWaring":'1.您即将联网并发起转出请求，请检查转出地址是否正确；',
  "transferConfirmWaring1":'2.避免转出失败和GAS消耗，请确保转出代币和GAS充足；',
  "transferConfirmWaring2":'3.避免链上机制清空DOT<1帐户的风险，请转出DOT确保转出后链上余额 >1。',
};